### ISSUE TITLE
When deleting a resource from a dataset, the corresponding lfs file should be deleted

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-gitdatahub#15]
If a resource is deleted from the dataset, after updating the `datapackage.json` we should also remove the lfs pointer from the repository.

## Acceptance Criteria
- [x] When a Resource is deleted from a dataset, the corresponding file is also deleted from the repository.

## Task
- [x] Implement the `before_delete` method from the `IResourceController` interface to hook the deletion logic
- [x] Implement a new method in `ckan_to_git.py` to remove the the file from the repository.

## Analysis

The [IResourceController](https://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IResourceController.before_delete) contains a method to add custom logic `before_delete` the Resource is deleted from the database which receives the resource to be deleted as a parameter. It also has another one `after_delete` but this does not receive the deleted resource so an extra logic will be neccesary to detect which file to delete from the repository.

TODO: How do we manage consistency between repository/metastore? What if we delete a Resource from the repository in `before_delete` but the delete process in CKAN fails?
