### ISSUE TITLE
Planning: Refactor of the ckan_to_git module

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-gitdatahub#23]
The module works as expected for a first MVP but lots of improvements can be done to its architecture and overall usage. 

Now it is hard to test as it requires a token and calls to the GitHub API, there are some extensions that can help with this like [vcrpy](https://github.com/kevin1024/vcrpy) but probably worth discussing if are we going to implement our own wrapper.

## Task
* [ ] Review the code and write down improvements
* [x] Define requirements for #21 
* [x] Define requirements for #14 
* [ ] Refactor to use an App Key

## Analysis

**Comment by shevron** [comment]
I didn't look into the code in detail (let me know if you want me to and when) but at first glance the first thing you should do is decouple the CKAN plugin from `CKANGitClient` and break that class down into an abstract / interface and concrete implementation for GitHub. I'm sure there are also methods in this class which are not GitHub specific and can be factored out of it (e.g. the logic to create LFS pointer files). 

The process for doing something like this should be, more or less:
- Define what is the role of an *abstract* Git client class, and what methods it should expose to consumers - what are the roles of each method (your main consumer is the CKAN plugin).
- Write an abstract class that defines the API, documenting (in pydoc, I also like to use type annotations) the purpose, arguments and return types of each method in this class
- Modify the plugin classes to *accept* an instance of this class without knowing specifically what subclass is in use. This allows us to later replace the Git client, or use a mock client in testing. 
- Since CKAN plugin classes are not instantiated by us, we cannot use classic dependency injection to inject a GitClient object. We can, however, implement some kind of factory style function that instantiates and returns such an object based on CKAN configuration (class and dict of arguments to pass to it can come from config). Maybe there is a better way but I don't know it. 
- Implement a concrete implementation of that abstract interface for GitHub based on the GH API. 
- Look for code in that implementation that is not GitHub specific and factor it out - either to a composed object, to external utility functions or to a base parent class that can be shared by other client implementations. 

I can help with all of that if needed.
