### ISSUE TITLE
Write data files to git as lfs items

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-gitdatahub#9]
We need to write each resource data file as lfs items under the `data/` folder of the repository. In order to do that we need to:

## Acceptance Criteria

* [x] For each one of the dataset resources stored in a git lfs server we have a corresponding lfs item in the `data` folder

## Tasks

* [x] Identify the files stored in the git lfs server
* [x] Create a lfs pointer file according to the specifications (see analysis)
* [x] Commit the lfs pointers to the Repository
* [x] Refactor the `.gitattributes` logic to write a file with only one line: `data/* filter=lfs diff=lfs merge=lfs -text`

## TODO:
 - How do we identify correctly which files will have a lfs pointer?

Resouces has a `url_type` field that can be used to detect if the resource has been upload or if it is an URL:

```python
if resource['url_type'] is None:
    # The Resource is a URL, no lfs pointer needed, just the link in the `datapackage.json`
else if resource['url_type'] is 'upload':
    # The Resource has been uploaded to CKAN probably we will have to add custom logic here to see if it has been uploaded to the git-lfs server
```

 - What happens with the files we are not uploading to a git lfs server? We just commit the file directly to the repo?

## Analysis

The specifications of the files to be written for each file stored in git lfs can be found [here]( https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md) but the basic structure we need to write for each file is:
```
version https://git-lfs.github.com/spec/v1
oid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393
size 12345
(ending \n)
```

So for example, given a dataset with 2 resources `data-1.csv` and `data-2.csv` we should have 2 files in the data folder with it's corresponding `oid sha256` and `size`.

```
data/
   - data-1.csv
   - data-2.csv
```

A basic pseudo-code to identify the files this can be:
```python
def process_dp_to_identify_resources_in_cloud_lfs(dp)
  for each resource in dp.resources:
    # if we are only storing in our own cloud storage this check is not needed => always true
    if resource in "our" cloudstorage: # resource.path matches cloud storage url ...
      then assume this is stored in git lfs compatible manner ...
        #assume no sub directories ...
        resource.path = "filename.ext"
        files_to_write_to_git.append({
          path: "filename.ext",
          hash: "...",
          size: "..."
        })
```

**Comment by shevron** [comment]
You can see a reference implementation in JS here: https://gitlab.com/datopian/experiments/git-lfs-datahub-client/-/blob/master/src/lib/lfsClient.js#L11

Note that you will also need to write `.gitattributes` and `.lfsconfig` files next to the `datapackage.json` file to be 100% compatible with native Git / Git LFS. You can see an implementation of them in the same file linked above.

**Comment by shevron** [comment]
I am not aware of a situtation in which we are not uploading with the Git LFS server BTW. The original flow we described assumes we do. However, if we are not, I can suggest that:

* Every file that is passed to CKAN (and not uploaded by the client to storage via Git LFS) as part of the "update resource" / "create resource" request will be assumed to not be in Git LFS
* Every file that is not in Git LFS can be committed directly to the repo
* This should only happen for small (say 500kb max), textual files IMHO.

**Comment by shevron** [comment]
If we are going for option 1, we probably want to do a few things:
* Put logic in the client (probably configured via a CKAN option -> CKAN template -> JS) to decide when to push to LFS and when not. This could be a purely size based decision or also on file types. 
* Have some validation in CKAN new resource / update resource form to ensure files are not uploaded directly to CKAN unless they meed a certain criteria. This can be implemented in datopian/ckanext-external-storage at some point

But the more I think about it, the naive approach of always storing in LFS sounds better to me.

**Comment by uwaheed88** [comment]
@pdelboca @shevron @rufuspollock in the reference code we are using `file.contents` to update the SHA256 hash generated against a resource. How can I access the file contents of a resource? Or should I use resource_id or something like that to update the SHA256 hash generated?

**Comment by pdelboca** [comment]
To have a content addressable storage we depend on the SHA256 to be generated from the file content.

However, calculating it is not a responsibility of this extension, should be delivered in the `package_dict` as a field of its `resources` so we have to assume that if the file is stored in some cloudstorage there will be some sort of a `sha256` field in each resource. 

From a design perspective it is not good because we need to code assuming internal details of another system. Is there any protocol? How are we gonna design this interaction @shevron @rufuspollock ?

**Comment by pdelboca** [comment]
Gonna close this issue and open a new one to discuss how to properly identify the resources that we need to write into the Repository as lfs pointer files.
